In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Create tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.dtype

torch.int64

In [13]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,5,2]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 2]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 2]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

## Random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers


In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7242, 0.0823, 0.5477, 0.2370],
        [0.9069, 0.2897, 0.2236, 0.9079],
        [0.4947, 0.4675, 0.2295, 0.2270]])

In [19]:
random_image_size_tensor = torch.rand(size=(3, 224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [24]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [31]:
int_64_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_64_tensor.dtype

torch.int64

In [32]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device


In [33]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1028, 0.7618, 0.4233, 0.2629],
        [0.0427, 0.0966, 0.5098, 0.1580],
        [0.9379, 0.6377, 0.2506, 0.2396]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1028, 0.7618, 0.4233, 0.2629],
        [0.0427, 0.0966, 0.5098, 0.1580],
        [0.9379, 0.6377, 0.2506, 0.2396]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)
Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [35]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
tensor - 10

tensor([-9, -8, -7])

In [39]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:

The inner dimensions must match:
- (3, 2) @ (3, 2) won't work
- (2, 3) @ (3, 2) will work
- (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)

In [41]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.54 ms, sys: 98 µs, total: 1.64 ms
Wall time: 1.34 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 42.4 µs


tensor(14)

## One of the most common errors in deep learning: shape errors


In [47]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
#torch.matmul(tensor_A, tensor_B)

In [48]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [51]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [52]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [53]:
t_test = torch.tensor([[[7],
                         [8],
                         [9]],
                       [[1],
                         [5],
                         [0]]])
t_test.shape

torch.Size([2, 3, 1])

In [54]:
t_test.T, t_test.T.shape

<ipython-input-54-2599f4d90343>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3614.)
  t_test.T, t_test.T.shape


(tensor([[[7, 1],
          [8, 5],
          [9, 0]]]),
 torch.Size([1, 3, 2]))

In [55]:
trans = torch.transpose(t_test, 0, 1)
trans, trans.shape

(tensor([[[7],
          [1]],
 
         [[8],
          [5]],
 
         [[9],
          [0]]]),
 torch.Size([3, 2, 1]))

In [56]:
trans = torch.transpose(t_test, 1, 2)
trans, trans.shape

(tensor([[[7, 8, 9]],
 
         [[1, 5, 0]]]),
 torch.Size([2, 1, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [57]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [58]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [59]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [60]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [61]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [62]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [63]:
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(1)

In [65]:
x.argmax()

tensor(9)

In [66]:
x[9]

tensor(91)

In [67]:
x_test = torch.rand(2,3)
x_test

tensor([[0.4260, 0.9447, 0.0065],
        [0.1422, 0.5989, 0.0804]])

In [68]:
x_test.argmax()

tensor(1)

In [69]:
x_test.argmax(dim=1)

tensor([1, 1])

In [70]:
x_test[0][0], x_test[1][2]

(tensor(0.4260), tensor(0.0804))

## Reshaping, stacking, squeezing and unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [101]:
import torch
x = torch.arange(1.,10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [102]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [103]:
x_reshaped_test = x.reshape(3, 3)
x_reshaped_test, x_reshaped_test.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [104]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [105]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [106]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [112]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [113]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [78]:
x_reshaped_test = x.reshape(1, 1, 9)
x_reshaped_test, x_reshaped_test.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [79]:
x_squeezed_test = x_reshaped_test.squeeze()
x_squeezed_test, x_squeezed_test.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])


In [81]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [82]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [83]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [84]:
# permute returns a view
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing(selecting data from tensors)

In [114]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [115]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
x[0][0]

tensor([1, 2, 3])

In [116]:
x[0][1][1]

tensor(5)

In [88]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]
# same as x[:, 0, :]

tensor([[1, 2, 3]])

In [89]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [90]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [91]:
x[0,0,:]

tensor([1, 2, 3])

In [92]:
print(x[0][2][2])

tensor(9)


In [118]:
print(x[:,2,2])

tensor([9])


In [93]:
print(x[:,:,2])

tensor([[3, 6, 9]])


In [119]:
print(x[0, :, 2])

tensor([3, 6, 9])


## PyTorch tensors & Numpy

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [120]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's defualt datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [121]:
array.dtype

dtype('float64')

In [122]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [123]:
# change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [124]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [125]:
numpy_tensor.dtype

dtype('float32')

In [126]:
# change the tensor, what happens to numpy?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility  (trying to take random out of random)

In [127]:
torch.rand(3,3)

tensor([[0.0384, 0.5191, 0.9763],
        [0.3665, 0.4813, 0.9012],
        [0.0030, 0.6704, 0.1573]])

In [128]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9492, 0.2896, 0.0313, 0.5633],
        [0.1868, 0.9543, 0.6017, 0.1406],
        [0.2133, 0.5924, 0.3226, 0.9182]])
tensor([[0.4910, 0.0631, 0.4960, 0.3781],
        [0.7903, 0.2028, 0.3585, 0.1592],
        [0.1657, 0.2515, 0.6059, 0.6479]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [131]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs and make faster computations

### 1. Getting a GPU

1. Easiest - google colab
2. Use your own GPU - https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS...

In [1]:
!nvidia-smi

Wed Jan 10 11:07:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices - best practice: https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

In [8]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to CPU

In [11]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])